name: boileroom-chai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy<2.0
  - rdkit
  - pip
  - pip:
    - torch==2.5.1
    - chai_lab==0.6.1
    - hf_transfer==0.1.8
    - biotite>=1.0.1
    - fastapi
    - uvicorn
    - pydantic
