name: boileroom-boltz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy<2.0
  - pip
  - pip:
    - torch>=2.5.1,<2.7.0
    - pytorch-lightning
    - boltz==2.1.1
    - biotite>=1.0.1
    - fastapi
    - uvicorn
    - pydantic

